#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}-{branch}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: cd scripts; .\build.ps1 -Compile -verbose
  
# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - ps: .\pack.ps1 -verbose
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: build\cmder.zip
    name: cmderzip

  - path: build\cmder.7z
    name: cmder7z

  - path: build\cmder_mini.zip
    name: cmdermini

  - path: build\hashes.txt
    name: hashes

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: GRGxbim9O2W6+SrNumso7oO0y0a+5CbU/qwLkZmO0dRyM0VtlLRTdargizVcrswL
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
